### ISSUE TITLE
IP Sec tunnel Cisco IOS config

### ISSUE THREAD

**Issue by mohang2019** [kecorbin/ansible-vpn-router#1]
Hi,

I am new to Ansible and i am from virtualization domain i was having an requirement for automating the cisco router exactly what the code available in your repository, but not sure on how to use this code in my Ansible controller, please help me.

**Comment by jabelk** [comment]
Hi,

If you are new to ansible, I suggest going through some of the videos and trainings out there to get familiar with the basics. Kevin provides some sample inventory and playbook usage in this repo:
https://github.com/kecorbin/ansible-vpn-router#example-inventory
so once you are used to the mechanisms of Ansible, you can more easily tackle integrating in complex solutions like this one.
